# Particle source: optical photons
/gps/particle opticalphoton
/gps/energy 2.5 eV

#/gps/ene/type Bbody
#/gps/ene/temp 5700 K
#/gps/ene/min 0.1 eV
#/gps/ene/max 5 eV
#/gps/ene/gradient 1
#/gps/ene/intercept 1

# Spherical volume source
/gps/pos/type Volume
/gps/pos/shape Sphere
/gps/pos/centre 0. 0. 0. mm

# Sphere dimensions
/gps/pos/radius 2.5 cm
/gps/ang/type iso

# Direction of photons (collimated along +X)
/gps/direction 1 0 0

# Run
/run/beamOn 1000